<?php

//AUTENTICACIÓN DE USUARIOS

session_start(); //MANTENER DATOS EN TODA LA PÁGINA PARA SABER QUE EFECTIVAMENTE EL USUARIO ESTÁ LOGEADO

//LAS VARIABLES DE SESIÓN NOS SIRVEN PARA ALMACENAR INFORMACIÓN DE LA SESIÓN DEL USUARIO Y QUE SE PUEDA VER DESDE TODAS LAS PÁGINAS
//CUANDO CERRAMOS EL NAVEGADOR, SE PIERDE LA CONEXIÓN CON EL SERVIDOR Y POR TANTO LA SESIÓN SE PIERDE

$_SESSION["usuario"] = "develoteca"; //GUARDAMOS EN $_SESSION (VARIABLE DE SESIÓN) EL USUARIO Y EL ESTADO
$_SESSION["status"] = "logueado";

echo "Sesión iniciada"."<br/>";
echo "USUARIO: ".$_SESSION["usuario"]." - STATUS: ".$_SESSION["status"]."<br/>";


?>